# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dvg import rechnung_pb2 as dvg_dot_rechnung__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dvg/rechnung_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RechnungServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRechnung = channel.unary_unary(
                '/dvg.RechnungService/CreateRechnung',
                request_serializer=dvg_dot_rechnung__pb2.RechnungCreateRequest.SerializeToString,
                response_deserializer=dvg_dot_rechnung__pb2.RechnungCreateResponse.FromString,
                _registered_method=True)
        self.GetRechnungById = channel.unary_unary(
                '/dvg.RechnungService/GetRechnungById',
                request_serializer=dvg_dot_rechnung__pb2.RechnungIdRequest.SerializeToString,
                response_deserializer=dvg_dot_rechnung__pb2.RechnungIdResponse.FromString,
                _registered_method=True)
        self.MarkRechnungAsPaid = channel.unary_unary(
                '/dvg.RechnungService/MarkRechnungAsPaid',
                request_serializer=dvg_dot_rechnung__pb2.RechnungPaiedRequest.SerializeToString,
                response_deserializer=dvg_dot_rechnung__pb2.RechnungPaiedResponse.FromString,
                _registered_method=True)


class RechnungServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRechnung(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRechnungById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkRechnungAsPaid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RechnungServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRechnung': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRechnung,
                    request_deserializer=dvg_dot_rechnung__pb2.RechnungCreateRequest.FromString,
                    response_serializer=dvg_dot_rechnung__pb2.RechnungCreateResponse.SerializeToString,
            ),
            'GetRechnungById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRechnungById,
                    request_deserializer=dvg_dot_rechnung__pb2.RechnungIdRequest.FromString,
                    response_serializer=dvg_dot_rechnung__pb2.RechnungIdResponse.SerializeToString,
            ),
            'MarkRechnungAsPaid': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkRechnungAsPaid,
                    request_deserializer=dvg_dot_rechnung__pb2.RechnungPaiedRequest.FromString,
                    response_serializer=dvg_dot_rechnung__pb2.RechnungPaiedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dvg.RechnungService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dvg.RechnungService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RechnungService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRechnung(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dvg.RechnungService/CreateRechnung',
            dvg_dot_rechnung__pb2.RechnungCreateRequest.SerializeToString,
            dvg_dot_rechnung__pb2.RechnungCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRechnungById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dvg.RechnungService/GetRechnungById',
            dvg_dot_rechnung__pb2.RechnungIdRequest.SerializeToString,
            dvg_dot_rechnung__pb2.RechnungIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkRechnungAsPaid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dvg.RechnungService/MarkRechnungAsPaid',
            dvg_dot_rechnung__pb2.RechnungPaiedRequest.SerializeToString,
            dvg_dot_rechnung__pb2.RechnungPaiedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
