# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dvg/rechnung.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dvg/rechnung.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64vg/rechnung.proto\x12\x03\x64vg\"\x8b\x01\n\x15RechnungCreateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\naussteller\x18\x02 \x01(\t\x12\x12\n\nempfaenger\x18\x03 \x01(\t\x12\x0e\n\x06\x62\x65trag\x18\x04 \x01(\x01\x12\x19\n\x11\x61usstellungsdatum\x18\x05 \x01(\t\x12\x13\n\x0bist_bezahlt\x18\x06 \x01(\x08\"$\n\x16RechnungCreateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11RechnungIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"|\n\x12RechnungIdResponse\x12\x12\n\naussteller\x18\x01 \x01(\t\x12\x12\n\nempfaenger\x18\x02 \x01(\t\x12\x0e\n\x06\x62\x65trag\x18\x03 \x01(\x01\x12\x19\n\x11\x61usstellungsdatum\x18\x04 \x01(\t\x12\x13\n\x0bist_bezahlt\x18\x05 \x01(\x08\"\"\n\x14RechnungPaiedRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x15RechnungPaiedResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xed\x01\n\x0fRechnungService\x12I\n\x0e\x43reateRechnung\x12\x1a.dvg.RechnungCreateRequest\x1a\x1b.dvg.RechnungCreateResponse\x12\x42\n\x0fGetRechnungById\x12\x16.dvg.RechnungIdRequest\x1a\x17.dvg.RechnungIdResponse\x12K\n\x12MarkRechnungAsPaid\x12\x19.dvg.RechnungPaiedRequest\x1a\x1a.dvg.RechnungPaiedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dvg.rechnung_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECHNUNGCREATEREQUEST']._serialized_start=28
  _globals['_RECHNUNGCREATEREQUEST']._serialized_end=167
  _globals['_RECHNUNGCREATERESPONSE']._serialized_start=169
  _globals['_RECHNUNGCREATERESPONSE']._serialized_end=205
  _globals['_RECHNUNGIDREQUEST']._serialized_start=207
  _globals['_RECHNUNGIDREQUEST']._serialized_end=238
  _globals['_RECHNUNGIDRESPONSE']._serialized_start=240
  _globals['_RECHNUNGIDRESPONSE']._serialized_end=364
  _globals['_RECHNUNGPAIEDREQUEST']._serialized_start=366
  _globals['_RECHNUNGPAIEDREQUEST']._serialized_end=400
  _globals['_RECHNUNGPAIEDRESPONSE']._serialized_start=402
  _globals['_RECHNUNGPAIEDRESPONSE']._serialized_end=442
  _globals['_RECHNUNGSERVICE']._serialized_start=445
  _globals['_RECHNUNGSERVICE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
