syntax = "proto3";

package config;

service RechnungService {
  rpc CreateRechnung(CreateRechnungRequest) returns (CreateRechnungResponse);
  rpc CreateRechnungsposition(CreateRechnungspositionRequest) returns (CreateRechnungspositionResponse);
  rpc MarkRechnungAsPaid(MarkRechnungAsPaidRequest) returns (MarkRechnungAsPaidResponse);
}

message CreateRechnungRequest {
  int32 id = 1;
  string rechnungsnummer = 2;
  string ausstellungsdatum = 3;
  string aussteller = 4;
  string kundennummer = 5;
  string zahlungsziel = 6;
  string bemerkungen = 7;
  bool ist_bezahlt = 8;
}

message CreateRechnungResponse {
  int32 id = 1;
}

message CreateRechnungspositionRequest {
  int32 id = 1;
  int32 rechnung_id = 2;
  int32 rechnungsposition = 3;
  string beschreibung = 4;
  int32 menge = 5;
  string einheit = 6;
  double einzelpreis = 7;
}

message CreateRechnungspositionResponse {
  int32 id = 1;
}

message MarkRechnungAsPaidRequest {
  int32 id = 1;
}

message MarkRechnungAsPaidResponse {
  bool success = 1;
}
