syntax = "proto3";

package config;

service RechnungService {
  rpc CreateRechnung(RechnungCreateRequest) returns (RechnungCreateResponse);
  rpc GetRechnungById(RechnungIdRequest) returns (RechnungIdResponse);
  rpc MarkRechnungAsPaid(RechnungPaiedRequest) returns (RechnungPaiedResponse);
}

message RechnungCreateRequest {
  int32 id = 1;
  string rechnungsnummer = 2;
  string aussteller = 3;
  string kundennummer = 4;
  string empfaenger = 5;
  double betrag = 6;
  string ausstellungsdatum = 7;
  bool ist_bezahlt = 8;
}

message RechnungCreateResponse {
  int32 id = 1;
}

message RechnungIdRequest {
  int32 id = 1;
}

message RechnungIdResponse {
  string aussteller = 1;
  string empfaenger = 2;
  double betrag = 3;
  string ausstellungsdatum = 4;
  bool ist_bezahlt = 5;
}

message RechnungPaiedRequest {
  int32 id = 1;
}

message RechnungPaiedResponse {
  bool success = 1;
}
